### ISSUE TITLE
Create restaurants objects in "mockapi" tool.

### ISSUE THREAD

**Issue by mateusz-sz** [nokia-wroclaw/innovativeproject-togeather#11]
We need to have restaurants objects created in [`mockapi.io`](https://www.mockapi.io/), so that Angular app is able to fetch "fake" data from that site.

The structure of the restaurant object should contain at least:
– restaurant-name
– restaurant coordinates (float numbers), or address (string)
– some restaurant menu? [needs to be precised later]

Link to already existing project in mockapi:
https://www.mockapi.io/clone/5dd46cbf8b5e080014dc51a5

**Comment by a-jonak** [comment]
Create api route for getting restaurants with their coordinates. http://5dd7ed12505c590014d3b756.mockapi.io/api/v1/reataurants
