### ISSUE TITLE
Modify returned /api/lobbies response

### ISSUE THREAD

**Issue by mateusz-sz** [nokia-wroclaw/innovativeproject-togeather#59]
On route `/api/lobbies` application should accept:

When creating new lobby with POST:
```
{
	"restaurant_id": 1,
	"owner": 4,
	"expires": "2019-12-31T09:29:00Z",
	"address": "Szkolna 6"
}
```
Response:
```
{
    "id": 4,
    "restaurant": {
        "id": 1,
        "name": "Pizza Station",
        "menu": null,
        "address": ""
    },
    "owner": 4,
    "expires": "2019-12-31T09:29:00Z",
    "location": {
        "lat": 51.10916,
        "lon": 17.06319,
        "lobby_address": "Szkolna 6"
    }
}
```
Also when making GET on `/api/lobbies` Api should respond with above JSON

**Comment by mateusz-sz** [comment]
On route `/api/lobbies` application should accept:

When creating new lobby with POST:
`{
	"restaurant_id": 1,
	"owner": 4,
	"expires": "2019-12-31T09:29:00Z",
	"address": "Szkolna 6"
}`
Response:
`{
    "id": 4,
    "restaurant": {
        "id": 1,
        "name": "Pizza Station",
        "menu": null,
        "address": ""
    },
    "owner": 4,
    "expires": "2019-12-31T09:29:00Z",
    "lat": 51.10916,
    "lon": 17.06319,
    "lobby_address": "Szkolna 6"
}`
Also when making GET on `/api/lobbies` Api should respond with above JSON

**Comment by mateusz-sz** [comment]
First you will need to create new account on Mapquest to get API key.

Api for translating addresses to coordinates: https://developer.mapquest.com/
Documentation: https://developer.mapquest.com/documentation/geocoding-api/

**Comment by mpadlewski** [comment]
When using POST, in address field you have to specify also name of city and put number of street and building before street name.
So in your example: "6 Szkolna Wrocław"

API works better with such a format.
